import type { DecisionRecord } from "@/lib/types";

export const demoDecisions: DecisionRecord[] = [
  {
    id: "demo-portfolio-case-study",
    title: "Publish the portfolio case study before July",
    category: "Project",
    decisionDate: "2026-06-01",
    reviewDate: "2026-06-18",
    expectedOutcome: "The case study is live with screenshots, methods, and a short technical appendix.",
    confidencePercentage: 82,
    reasoning: "The app is mostly scoped and the writing outline is ready.",
    status: "reviewed",
    actualOutcomeStatus: "happened",
    satisfactionScore: 8,
    lessonLearned: "A narrow project story was easier to finish than a broad feature list.",
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-06-18T10:30:00.000Z",
  },
  {
    id: "demo-statistics-sprint",
    title: "Complete the Bayesian statistics sprint in one weekend",
    category: "Learning",
    decisionDate: "2026-06-03",
    reviewDate: "2026-06-10",
    expectedOutcome: "Finish two chapters and solve the marked exercises.",
    confidencePercentage: 88,
    reasoning: "The reading seemed short and the exercises looked familiar.",
    status: "reviewed",
    actualOutcomeStatus: "did_not_happen",
    satisfactionScore: 4,
    lessonLearned: "Exercise difficulty mattered more than chapter length.",
    createdAt: "2026-06-03T09:00:00.000Z",
    updatedAt: "2026-06-10T11:45:00.000Z",
  },
  {
    id: "demo-monitor-purchase",
    title: "Buy a used monitor after checking desk fit",
    category: "Purchase",
    decisionDate: "2026-06-05",
    reviewDate: "2026-06-19",
    expectedOutcome: "The monitor improves study sessions without crowding the desk.",
    confidencePercentage: 63,
    reasoning: "The price is good, but the desk space is uncertain.",
    status: "reviewed",
    actualOutcomeStatus: "partial",
    satisfactionScore: 6,
    lessonLearned: "Measure the setup before comparing prices.",
    createdAt: "2026-06-05T09:00:00.000Z",
    updatedAt: "2026-06-19T08:20:00.000Z",
  },
  {
    id: "demo-internship-application",
    title: "Send the data internship application this week",
    category: "Career",
    decisionDate: "2026-06-16",
    reviewDate: "2026-06-24",
    expectedOutcome: "Submit a tailored application with one DecisionOS paragraph.",
    confidencePercentage: 74,
    reasoning: "Resume and project links are ready, but the cover letter needs focus.",
    status: "pending",
    actualOutcomeStatus: null,
    satisfactionScore: null,
    lessonLearned: "",
    createdAt: "2026-06-16T09:00:00.000Z",
    updatedAt: "2026-06-16T09:00:00.000Z",
  },
  {
    id: "demo-capstone-topic",
    title: "Choose the capstone topic after comparing three ideas",
    category: "Project",
    decisionDate: "2026-06-20",
    reviewDate: "2026-07-01",
    expectedOutcome: "Select one idea with testable data and a clear README story.",
    confidencePercentage: 68,
    reasoning: "The DecisionOS scope is clearer than the two larger ideas.",
    status: "pending",
    actualOutcomeStatus: null,
    satisfactionScore: null,
    lessonLearned: "",
    createdAt: "2026-06-20T09:00:00.000Z",
    updatedAt: "2026-06-20T09:00:00.000Z",
  },
];
